# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: gestion-vehiculos
    container_name: gestion-vehiculos
    env_file:
      - ./.envs/.local/.postgres

    volumes:
      - gestion-vehiculos:/var/lib/postgresql/data
      # - drf-tutorials_data_backups:/backups
    ports:
      - 5434:5432

volumes:
  gestion-vehiculos:
  # drf-tutorials_data_backups:


