# Generated by Django 5.0.1 on 2024-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.IntegerField(choices=[(1, 'Rojo'), (2, 'Azul'), (3, 'Verde'), (4, 'Negro'), (5, 'Amarillo'), (6, 'Gris'), (7, 'Blanco')]),
        ),
    ]
